"""Shared fixtures. tests/generated/ is excluded from collection via pyproject."""

from __future__ import annotations

from pathlib import Path

import pytest

from qaia.domain.models import GeneratedFile, LlmTestArtifacts


@pytest.fixture
def sample_artifacts() -> LlmTestArtifacts:
    return LlmTestArtifacts(
        files=[
            GeneratedFile(
                filename="conftest.py",
                content="import os\nimport httpx\nimport pytest\n",
                description="fixtures (base_url, client)",
            ),
            GeneratedFile(
                filename="test_health.py",
                content="def test_health() -> None:\n    assert True\n",
                description="health check test",
            ),
        ],
        requirements=["pytest", "httpx"],
        notes="generated by a fake LLM in tests",
    )


@pytest.fixture
def sample_feature_path() -> Path:
    return Path(__file__).parent / "fixtures" / "sample.feature"
